background            #2a2a2a
foreground            #e6e4e3
selection_foreground  #3f4647
selection_background  #c8cccc
url_color             #c8cccc

#: black 000000 767676
color0  #2a2a2a
color8  #494949
#: red cc0403 f2201f
color1  #6b3c00
color9  #ff9205
#: green 19cb00 23fd00
color2  #c8cccc
color10 #e1e5e5
#: yellow cecb00 fffd00
color3  #e0c7ba
color11 #fadfd3
#: blue 0d73cc 1a8fff
color4  #4c5c5d
color12 #c0cecf
#: magenta cb1ed1 fd28ff
color5  #545a5a
color13 #c8cccc
#: cyan 0dcdcd 14ffff
color6  #6a5449
color14 #e0c7ba
#: white dddddd ffffff
color7  #c7cccc
color15 #e6e4e3

mark1_foreground #1f383a
mark1_background #d9e8e9
mark2_foreground #2c3335
mark2_background #e1e5e5
mark3_foreground #462e1f
mark3_background #fadfd3

active_tab_foreground #36494b
active_tab_background #c0cecf
inactive_tab_foreground #d3e1e2
inactive_tab_background #495a5b

active_border_color #c0cecf
inactive_border_color #36494b
# bell_border_color #ff5a00