alias yt="yt-dlp --no-playlist"
alias yt1="yt-dlp --audio-format best -o \"%(title)s.%(ext)s\" --extract-audio"
alias yt2="yt-dlp --yes-playlist"
alias c="clear"
alias ls="ls -Lahs --group-directories-first --color=tty"
alias sps="sudo pacman -S"
alias syu="sudo pacman -Syu"
alias spa="paru"
alias pyu="paru -Syu"
alias cyb="cyberdrop-dl -o /mnt/Blue/Cyberdrop"
alias ff="fastfetch"
alias pfl="papirus-folders -l"
alias pf="papirus-folders -C"
alias nvp="nordvpn connect netherlands"
alias nvd="nordvpn disconnect"
alias layout="cd /home/matt/Arch-Hyprland/.config/hypr && sh layout.sh && cd"
alias kt='kitten themes && kill -SIGUSR1 $KITTY_PID'
alias hq="git --git-dir=/home/matt/HyprQuick/ --work-tree=$HOME"