$image = Null

$background = rgba(2a2a2aff)

$error = rgba(ffb8afff)

$error_container = rgba(cb000dff)

$inverse_on_surface = rgba(444444ff)

$inverse_primary = rgba(617173ff)

$inverse_surface = rgba(e6e4e3ff)

$on_background = rgba(e6e4e3ff)

$on_error = rgba(a70007ff)

$on_error_container = rgba(ffdcd8ff)

$on_primary = rgba(36494bff)

$on_primary_container = rgba(d3e1e2ff)

$on_primary_fixed = rgba(1f383aff)

$on_primary_fixed_variant = rgba(4c5c5dff)

$on_secondary = rgba(3f4647ff)

$on_secondary_container = rgba(e2e7e7ff)

$on_secondary_fixed = rgba(2c3335ff)

$on_secondary_fixed_variant = rgba(545a5aff)

$on_surface = rgba(e6e4e3ff)

$on_surface_variant = rgba(c7ccccff)

$on_tertiary = rgba(564035ff)

$on_tertiary_container = rgba(f3d9ccff)

$on_tertiary_fixed = rgba(462e1fff)

$on_tertiary_fixed_variant = rgba(6a5449ff)

$outline = rgba(969d9dff)

$outline_variant = rgba(535b5bff)

$primary = rgba(c0cecfff)

$primary_container = rgba(495a5bff)

$primary_fixed = rgba(d9e8e9ff)

$primary_fixed_dim = rgba(c0cecfff)

$scrim = rgba(000000ff)

$secondary = rgba(c8ccccff)

$secondary_container = rgba(565c5cff)

$secondary_fixed = rgba(e1e5e5ff)

$secondary_fixed_dim = rgba(c8ccccff)

$shadow = rgba(000000ff)

$source_color = rgba(394647ff)

$surface = rgba(2a2a2aff)

$surface_bright = rgba(4c4c4cff)

$surface_container = rgba(343636ff)

$surface_container_high = rgba(3f3f3fff)

$surface_container_highest = rgba(494949ff)

$surface_container_low = rgba(313333ff)

$surface_container_lowest = rgba(262626ff)

$surface_dim = rgba(2a2a2aff)

$surface_tint = rgba(c0cecfff)

$surface_variant = rgba(535b5bff)

$tertiary = rgba(e0c7baff)

$tertiary_container = rgba(675246ff)

$tertiary_fixed = rgba(fadfd3ff)

$tertiary_fixed_dim = rgba(e0c7baff)
