## --------------------------------------------------------- ##

# Import modular configuration files #
source=./colors.conf # Matugen color generation
source=./monitors.conf # Monitor configuration
source=./environment.conf # Environment Variables
source=./startup.conf # Applications loaded at startup
source=./appearance.conf # Appearance settings
source=./inputs.conf # Input settings
source=./behaviour.conf # Behaviour settings
source=./myanimationslayouts.conf 
source=./workspacerules.conf # Workspace rules
source=./windowrules.conf # Window rules
source=./keybindings.conf # Keybinds
