general {
    lock_cmd = /home/matt/.local/share/quickshell-lockscreen/lock.sh     # what to run when loginctl or anything calls to lock
}

listener {
    timeout = 300
     # in seconds
    on-timeout = loginctl lock-session
    on-resume = notify-send "Welcome back!"
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}