general {
    layout = scrolling
}

animations {    
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsIn, 1, 15, default, gnomed
    animation = windowsOut, 1, 12, default, popin 30%
    animation = windowsMove, 1, 12, default, slide
    animation = border, 1, 10, default
    animation = fade, 1, 15, default
    animation = workspaces, 1, 15, default, slidefadevert
    animation = specialWorkspace,1,15,default,slidevert
    animation = specialWorkspaceOut,1,20,default,slidevert
}    

dwindle {
    pseudotile = true
    force_split = 1
    preserve_split = true
    smart_split = true
    smart_resizing = true
    permanent_direction_override = false
    special_scale_factor = 1
    split_width_multiplier = 1.0
    use_active_for_splits = true
    default_split_ratio = 1
    split_bias = 1
    precise_mouse_move = true
}

master {
    allow_small_split = false
    special_scale_factor = 0.9
    mfact = 0.6
    new_status = inherit
    new_on_top = true
    new_on_active = none
    orientation = left
    slave_count_for_center_master = 2
    center_master_fallback = left
    smart_resizing = true
    drop_at_cursor = true
    always_keep_position = false
}

scrolling {
    fullscreen_on_one_column = false
    column_width = 1
    focus_fit_method = 1
    follow_focus = true
    follow_min_visible = 1
    explicit_column_widths = 0.333, 0.5
    #wrap_focus = true
    #wrap_swapcol = true
    direction = right
}

layout {
    single_window_aspect_ratio = 16 9
    single_window_aspect_ratio_tolerance = 0.1
}