# Universal rules

windowrule = match:class kitty, opacity 0.75 0.6

# Workspace 1 Window Rules - Browsers
windowrule = match:class app.zen_browser.zen, workspace 1
windowrule = match:class app.zen_browser.zen, opacity 0.9
windowrule = match:class app.zen_browser.zen, fullscreen 1
windowrule = match:class app.zen_browser.zen, match:title Extension: (Bitwarden Password Manager) - Bitwarden — Zen Browser, float on, size 200 700

# Workspace 2 Window Rules - Empty Workspace

# Workspace 3 Window Rules - File Browser
windowrule = match:class org.kde.krusader, workspace 3 silent
windowrule = match:class org.kde.krusader, opacity 0.70 0.6

# Workspace 4 Window Rules - Text Editors
windowrule = match:class Emacs, workspace 4
windowrule = match:class Emacs, opacity 0.75 0.75
windowrule = match:class codium, workspace 4
windowrule = match:class codium, opacity 0.9
windowrule = match:class Claude, workspace 4
windowrule = match:class Claude, opacity 0.8

# Workspace 5 Window Rules - Games
windowrule = match:class steam, workspace 5
windowrule = match:class steam, opacity 0.7
windowrule = match:class steam, match:title Friends List, float 1
windowrule = match:class steam, match:title Steam - News, float 1
windowrule = match:class steam, match:title Steam - News, center 1

# Workspace 6 Window Rules - Server
windowrule = match:class librewolf, workspace 6
windowrule = match:class librewolf, opacity 0.9 0.6
windowrule = match:class chromium, workspace 6
windowrule = match:class chromium, opacity 0.9 0.6
windowrule = match:class chromium, no_initial_focus on
windowrule = match:class remote-viewer, workspace 6

# Workspace 7 Window Rules - Discord
windowrule = match:class discord, workspace 7
windowrule = match:class discord, opacity 0.8
windowrule = match:class discord, no_initial_focus on

# Workspace 8 Window Rules - Media
windowrule = match:class com.github.iwalton3.jellyfin-media-player, workspace 8
windowrule = match:class com.github.iwalton3.jellyfin-media-player, fullscreen 1
windowrule = match:class com.github.iwalton3.jellyfin-media-player, content video
windowrule = match:class Plex, workspace 8
windowrule = match:class Plex, fullscreen 1
windowrule = match:class Plex, content video

# Workspace 9 Window Rules - Empty Workspace

# Workspace 10 Window Rules - Parsec
windowrule = match:class parsecd, workspace 10
windowrule = match:class parsecd, maximize 1

# Special Workspaces
windowrule = match:class font-manager, workspace special:misc
windowrule = match:class pcmanfm-qt, workspace special:dolphin silent
windowrule = match:class pcmanfm-qt, opacity 0.8 0.65
windowrule = match:class com.plexamp.Plexamp, workspace special:audio
windowrule = match:class com.plexamp.Plexamp, opacity 0.8 0.8
windowrule = match:class firefox, workspace special:browser

# File Picker
windowrule = match:class (?i)xdg-desktop-portal-gtk, float on
windowrule = match:class (?i)xdg-desktop-portal-gtk, center on
windowrule = match:class (?i)xdg-desktop-portal-gtk, border_size 0
windowrule = match:class Xdg-desktop-portal-gtk, match:title Open Files, size 1400 850
windowrule = match:class xdg-desktop-portal-gtk, match:title  - Settings — Zen Browser, size 1400 850
