# Layer Rules
layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.3, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.3, match:namespace swaync-notification-window
#layerrule = blur on, match:namespace hyprquickpaper
layerrule = dim_around on, match:namespace hyprquickpaper
layerrule = match:namespace rofi, blur on
layerrule = match:namespace rofi, dim_around on

# Special Workspace Rules
workspace = special:kitty, gapsout:100, border:false
workspace = special:browser, gapsout:50, border:false
workspace = special:audio, gapsout:200, border:false
workspace = special:dolphin, gapsout:100, border:false
workspace = special:misc, gapsout:80, border:false
workspace = special:wallpaper, gapsout:185, border:false

# Regular Workspace Rules

